export const gameData = [
  { country: 'Francia', capital: 'París' },
  { country: 'Alemania', capital: 'Berlín' },
  { country: 'Italia', capital: 'Roma' },
  { country: 'España', capital: 'Madrid' },
  { country: 'Portugal', capital: 'Lisboa' },
  { country: 'Reino Unido', capital: 'Londres' },
  { country: 'Grecia', capital: 'Atenas' },
  { country: 'Países Bajos', capital: 'Ámsterdam' },
  { country: 'Bélgica', capital: 'Bruselas' },
  { country: 'Austria', capital: 'Viena' },
  { country: 'Suiza', capital: 'Berna' },
  { country: 'Polonia', capital: 'Varsovia' },
  { country: 'República Checa', capital: 'Praga' },
  { country: 'Hungría', capital: 'Budapest' },
  { country: 'Suecia', capital: 'Estocolmo' },
  { country: 'Noruega', capital: 'Oslo' },
  { country: 'Dinamarca', capital: 'Copenhague' },
  { country: 'Finlandia', capital: 'Helsinki' },
  { country: 'Irlanda', capital: 'Dublín' },
  { country: 'Rumania', capital: 'Bucarest' }
];
